== Twitter Streams Source Application

This creates twitter stream queries and posts tweets to a riff topic via the riff http-gateway

* `POST /streams` creates a new stream , with no request body will create a default sample stream.

For filtered queries

* `POST /streams {"language":"en", "streamType":"FILTER", "track":<comma-delimited-key-words>,
"follow":<comma-delimited-usernames>}`

* GET /streams - get query properties for all running streams
* GET /stream/{id} - get query properties for the stream

* DELETE /streams - destroy all streams
* DELETE /stream/{id} - destroy a stream

[NOTE]
To run this app you need to provid valid https://developer.twitter.com/en/docs/basics/authentication/guides/access-tokens[twitter credentials]

=== Running Standalone

You can run this app locally. You will need a running riff FaaS platform, and the riff http-gateway host and port.
The easiest way to get this is ` riff publish -i foo -d 0`  using a non-existent input topic.  You'll see a message
Posting to http://127.0.0.1:30365/messages/foo

```
$ ./mvnw clean package

$ java -jar target/twitter-source-0.0.1-SNAPSHOT.jar \
--twitter.credentials.consumerKey= \
--twitter.credentials.consumerKeySecret= \
--twitter.credentials.accessToken= \
--twitter.credentials.consumerKeySecret =

--riff.gateway.host=<host>
--riff.gateway.port=<riff-external-port>
--riff.gateway.topic=<topic>
```

Where the default host is `localhost`, default topic is `tweets`.

Alternatively you can set these values in `application.properties` before building.

When the app starts, it is waiting to start one or more twitter streams, each of which will be fed to the configured
topic. For example

```
$  $ curl -i -H'Content-type:application/json' http://localhost:8080/streams -d'{"language":"en"}'
  HTTP/1.1 201 Created
  transfer-encoding: chunked
  Content-Type: application/json;charset=UTF-8

  1
```
To terminate this stream:

```
$ curl http://localhost:8080/stream/1 -X DELETE
```
or to terminate all streams:

```
$ curl http://localhost:8080/streams -X DELETE
```

To start a filtered stream:

```
$curl -i -H'Content-type:application/json' http://localhost:8080/streams -d'{"language":"en","streamType":"FILTER","track":"@realDonaldTrump,#POTUS,'''Donald Trump'''}'
--riff.gateway.host=<riff-external-ip>
--riff.gateway.port=<riff-external-port>
--riff.gateway.topic=tweets

```
or you can provide these values in `application.properties` before building.
